version: '3.4'

networks:
  tile-server-network:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ELASTIC_PASSWORD: 1234
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - tile-server-network

  kibana:
    container_name: kibana
    image: kibana:8.13.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      elasticsearch.ssl.verificationMode: none
    networks:
      - tile-server-network
  
  gdd-proxy-server:
    container_name: gdd-proxy-server
    ports:
     - 8080:8080
     - 8081:8081
    build:
      context: .
      dockerfile: GeoDownloadDefence/Gdd.HttpApi/Dockerfile
    environment:
      - "TileServer:Url=http://gdd-tile-server:8082"
      - "ElasticSearch:Url=http://elasticsearch:9200"
      - "ElasticSearch:Index=tile-server-index"
      - "Sqlite:ConnectionString=DataSource=/data/gdd/gdd-sqlite.db"
    command: -c /bin/bash -p 'mkdir /data && mkdir /data/gdd'
    networks:
      - tile-server-network

  gdd-tile-server:
    container_name: gdd-tile-server
    ports:
      - 8082:8080
      - 8083:8081
    build:
      context: .
      dockerfile: ./TestTileServer/TileServerApi/Dockerfile
    environment:
      - "Tiles:LocalStoragePath=/data/gdd/tiles"
    volumes:
      - ./TestTileServer/Data:/data/gdd/tiles


volumes:
  elasticsearch_volume:
